FROM python:3.10-slim

RUN apt-get update && apt-get install -y ffmpeg python3-pip && \
    pip3 install yt-dlp && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY ./scripts /app/scripts

CMD ["tail", "-f", "/dev/null"]